#!/bin/bash 
# easy openconnect 

CONFIG_DIR=$HOME/.config/easyoc

config=user

if [ ! -d "${CONFIG_DIR}" ]; then
    mkdir ${CONFIG_DIR}
fi

if ! type openconnect oathtool &> /dev/null; then
    echo "openconnect 或 oathtool 未安装！"
    exit 1
fi

stop() {
    sudo kill -15 `ps ax | grep openconnect | grep -v grep | awk '{print$1}'` &> /dev/null
    echo "停止成功！"
}

status() {
    if ps ax | grep openconnect | grep -v grep &> /dev/null; then
        echo "运行中..."
    else
        echo "未运行！"
    fi
}


config() {

    echo "开始配置 OpenConnect ..."
    while [ -z "${config}" ]; do
        read -p "请输入配置名称[默认user]：" config
    done
    while [ -z "${url}" ]; do
        read -p "请输入连接地址[带上端口]：" url
    done
    while [ -z "${group}" ]; do
        read -p "请输入认证用户组：" group
    done
    while [ -z "${username}" ]; do
        read -p "请输入用户名：" username
    done
    while [ -z "${password}" ]; do
        read -s -p "请输入密码[无回显]：" password
    done
    echo
    read -s -p "请输入 OTP 密钥[无回显，为空则不启用]：" otp
    echo
    cat > ${CONFIG_DIR}/${config:-user} <<-EOF
OC_URL=${url}
OC_GROUP=${group}
OC_USERNAME=${username}
OC_PASSWORD=`echo -n ${password} | base64`
OC_OTP=`echo -n ${otp} | base64`
EOF
    cat <<-EOF
配置添加成功！
你也可以修改配置文件：${CONFIG_DIR}/${config:-user}
如果需要停止服务，执行命令：easyoc stop
如果需要重置配置，执行命令：easyoc reset
EOF

}

start() {

    if [ ! -f "${CONFIG_DIR}/${config}" ]; then
        config
    fi

    if ps ax | grep openconnect | grep -v grep &> /dev/null; then
        echo "程序已运行！"
        exit 1
    fi

    echo "开始连接 OpenConnect ..."
    source ${CONFIG_DIR}/${config}

    if [ -n "${OC_OTP}" ]; then
        otp_password=$(oathtool --totp -b `echo -n ${OC_OTP} | base64 -d`)
    fi
    echo "连接时需要使用管理员，可能会要求输入电脑密码."
    password="$(echo -n ${OC_PASSWORD} | base64 -d)${otp_password}"
    echo "${password}" | sudo openconnect -q -b ${OC_URL} -u ${OC_USERNAME} --authgroup=${OC_GROUP} --passwd-on-stdin &> /dev/null

    if [ $? -eq 0 ]; then
        echo "连接成功！"
    else
        echo "连接失败！请检查配置${CONFIG_DIR}/${config}或网络！"
    fi

}

help() {
    echo "Usage: $0 [-c <config>] [start|stop|status|config|help|list|del]"
}

list() {
    echo "配置列表："
    ls ${CONFIG_DIR}
}

del() {
    if [ -f "${CONFIG_DIR}/${config}" ]; then
        rm -f ${CONFIG_DIR}/${config}
        echo "配置删除成功！"
    else
        echo "配置不存在！"
    fi
}

while getopts "c:" opt; do
  case $opt in
    c)
        config=$OPTARG
        ;;
    \?)
        exit 1
        ;;
  esac
done

# 剔除已解析的参数
shift $((OPTIND-1))

case "${1}" in
    start) start ;;
    stop) stop ;;
    status) status ;;
    config) config ;;
    list) list ;;
    del) del ;;
    help) help ;;
    *) start ;;
esac