#!/bin/bash
source helper
# GITHUB_TOKEN
# GIT_USER_NAME
# GIT_USER_EMAIL
# GHUP_REPO
assert_nil "GITHUB_TOKEN" "GIT_USER_NAME" "GIT_USER_EMAIL" "GHUP_REPO" && exit

REMOTE_DIR=$1
shift 1

NOW_DATE="$(date "+%Y-%m-%d %H:%M:%S")"

API_URL=https://api.github.com/repos/${GIT_USER_NAME}/${GHUP_REPO}/contents/${REMOTE_DIR}

for FILE_PATH in $@; do
	content=$(base64 ${FILE_PATH} | tr -d '\n')
	FILE_NAME=$(basename ${FILE_PATH})
	res=`curl -s -X PUT -H "Authorization: token ${GITHUB_TOKEN}" \
		-H "Accept: application/vnd.github.v3+json" \
		--data '{"message":"message","content":"'${content}'"}' ${API_URL}/${FILE_NAME}`
	if echo "$res" | grep download_url &> /dev/null; then
		echo "https://cdn.jsdelivr.net/gh/${GIT_USER_NAME}/${GHUP_REPO}/${REMOTE_DIR}/${FILE_NAME}"
	else
		echo "上传文件${FILE_PATH}失败，可能文件已存在！"
		# echo "$res"
	fi
done